# Generated by Django 3.1.4 on 2021-08-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('modifiedAt', models.DateField(auto_now=True)),
                ('headerColor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateField(auto_now=True)),
                ('isFinished', models.BooleanField(default=False)),
                ('taskBar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taskbar')),
            ],
        ),
    ]
